version: '3.5'
services:
  puppeeteer:
    container_name: puppeeteer
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    tty: true
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

# Not to share node_modules/
volumes:
  node_modules:
    driver: 'local'
